// Auto Insurance Policy Template
// Standard auto insurance policy document with coverage details and declarations

import type { Template } from '@/lib/types/document.types';
import {
  createTextLabelProperties,
  createTextFieldProperties,
  createDateFieldProperties,
  createCheckboxProperties,
  createTableProperties,
  createParagraphProperties,
  createSignatureBoxProperties,
  createDividerProperties,
} from '../defaults';

export const AUTO_INSURANCE_BASIC: Template = {
  id: 'auto-insurance-basic',
  name: 'Auto Insurance Policy',
  description: 'Standard auto insurance policy document with coverage details and declarations',
  category: 'insurance',
  isBuiltIn: true,
  createdAt: '2025-01-01T00:00:00Z',
  updatedAt: '2025-01-01T00:00:00Z',
  content: {
    pages: [
      {
        id: 'page-1',
        pageNumber: 1,
        headerType: 'firstPage',
        footerType: 'default',
        components: [
          {
            id: 'title-1',
            type: 'text-label',
            position: { x: 20, y: 10 },
            size: { width: 170, height: 12 },
            properties: createTextLabelProperties({
              content: 'AUTO INSURANCE POLICY',
              fontSize: 24,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'center',
            }),
          },
          {
            id: 'subtitle-1',
            type: 'text-label',
            position: { x: 20, y: 25 },
            size: { width: 170, height: 8 },
            properties: createTextLabelProperties({
              content: 'Declarations Page',
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#666666',
              textAlign: 'center',
            }),
          },
          {
            id: 'divider-1',
            type: 'divider',
            position: { x: 20, y: 38 },
            size: { width: 170, height: 1 },
            properties: createDividerProperties({
              orientation: 'horizontal',
              thickness: 2,
              color: '#2563eb',
            }),
          },
          {
            id: 'policy-number-label',
            type: 'text-label',
            position: { x: 20, y: 48 },
            size: { width: 40, height: 6 },
            properties: createTextLabelProperties({
              content: 'Policy Number:',
              fontSize: 11,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#374151',
              textAlign: 'left',
            }),
          },
          {
            id: 'policy-number-field',
            type: 'text-field',
            position: { x: 65, y: 46 },
            size: { width: 60, height: 10 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'policy_number',
              placeholder: 'POL-XXXXX-XX',
              required: true,
              fontSize: 11,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'effective-date-label',
            type: 'text-label',
            position: { x: 20, y: 62 },
            size: { width: 40, height: 6 },
            properties: createTextLabelProperties({
              content: 'Effective Date:',
              fontSize: 11,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#374151',
              textAlign: 'left',
            }),
          },
          {
            id: 'effective-date-field',
            type: 'date-field',
            position: { x: 65, y: 60 },
            size: { width: 50, height: 10 },
            properties: createDateFieldProperties({
              label: '',
              fieldName: 'effective_date',
              format: 'MM/DD/YYYY',
              required: true,
            }),
          },
          {
            id: 'expiration-date-label',
            type: 'text-label',
            position: { x: 125, y: 62 },
            size: { width: 35, height: 6 },
            properties: createTextLabelProperties({
              content: 'Expiration:',
              fontSize: 11,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#374151',
              textAlign: 'left',
            }),
          },
          {
            id: 'expiration-date-field',
            type: 'date-field',
            position: { x: 160, y: 60 },
            size: { width: 50, height: 10 },
            properties: createDateFieldProperties({
              label: '',
              fieldName: 'expiration_date',
              format: 'MM/DD/YYYY',
              required: true,
            }),
          },
          {
            id: 'insured-section-title',
            type: 'text-label',
            position: { x: 20, y: 80 },
            size: { width: 170, height: 8 },
            properties: createTextLabelProperties({
              content: 'Named Insured',
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'insured-name-field',
            type: 'text-field',
            position: { x: 20, y: 92 },
            size: { width: 170, height: 12 },
            properties: createTextFieldProperties({
              label: 'Full Name',
              fieldName: 'insured_name',
              placeholder: 'Enter full legal name',
              required: true,
              fontSize: 11,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'insured-address-field',
            type: 'text-field',
            position: { x: 20, y: 110 },
            size: { width: 170, height: 12 },
            properties: createTextFieldProperties({
              label: 'Address',
              fieldName: 'insured_address',
              placeholder: 'Street address, City, State, ZIP',
              required: true,
              fontSize: 11,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'vehicle-section-title',
            type: 'text-label',
            position: { x: 20, y: 132 },
            size: { width: 170, height: 8 },
            properties: createTextLabelProperties({
              content: 'Vehicle Information',
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'vehicle-table',
            type: 'table',
            position: { x: 20, y: 144 },
            size: { width: 170, height: 40 },
            properties: createTableProperties({
              columnDefinitions: [
                { type: 'relative', width: 1 },
                { type: 'relative', width: 2 },
                { type: 'relative', width: 2 },
                { type: 'relative', width: 3 },
              ],
              headers: ['Year', 'Make', 'Model', 'VIN'],
              data: [
                ['', '', '', ''],
                ['', '', '', ''],
              ],
              showHeader: true,
              borderColor: '#d1d5db',
              headerBackground: '#f3f4f6',
            }),
          },
          {
            id: 'coverage-section-title',
            type: 'text-label',
            position: { x: 20, y: 195 },
            size: { width: 170, height: 8 },
            properties: createTextLabelProperties({
              content: 'Coverage Summary',
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'coverage-liability',
            type: 'checkbox',
            position: { x: 20, y: 208 },
            size: { width: 80, height: 8 },
            properties: createCheckboxProperties({
              label: 'Liability Coverage',
              fieldName: 'coverage_liability',
              defaultChecked: true,
            }),
          },
          {
            id: 'coverage-collision',
            type: 'checkbox',
            position: { x: 110, y: 208 },
            size: { width: 80, height: 8 },
            properties: createCheckboxProperties({
              label: 'Collision Coverage',
              fieldName: 'coverage_collision',
              defaultChecked: false,
            }),
          },
          {
            id: 'coverage-comprehensive',
            type: 'checkbox',
            position: { x: 20, y: 220 },
            size: { width: 80, height: 8 },
            properties: createCheckboxProperties({
              label: 'Comprehensive',
              fieldName: 'coverage_comprehensive',
              defaultChecked: false,
            }),
          },
          {
            id: 'coverage-uninsured',
            type: 'checkbox',
            position: { x: 110, y: 220 },
            size: { width: 80, height: 8 },
            properties: createCheckboxProperties({
              label: 'Uninsured Motorist',
              fieldName: 'coverage_uninsured',
              defaultChecked: false,
            }),
          },
        ],
      },
      {
        id: 'page-2',
        pageNumber: 2,
        headerType: 'default',
        footerType: 'default',
        components: [
          {
            id: 'terms-title',
            type: 'text-label',
            position: { x: 20, y: 10 },
            size: { width: 170, height: 10 },
            properties: createTextLabelProperties({
              content: 'Terms and Conditions',
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'terms-content',
            type: 'paragraph',
            position: { x: 20, y: 25 },
            size: { width: 170, height: 120 },
            properties: createParagraphProperties({
              content:
                'This policy is a legal contract between you and the insurance company. Please read all pages carefully.\n\n1. INSURING AGREEMENT: We will pay damages for bodily injury or property damage for which any covered person becomes legally responsible because of an auto accident.\n\n2. DEFINITIONS: Throughout this policy, "you" and "your" refer to the named insured shown in the Declarations. "We," "us," and "our" refer to the Company providing this insurance.\n\n3. TERRITORY: This policy applies only to accidents and losses which occur during the policy period within the United States of America, its territories or possessions, or Canada.\n\n4. POLICY PERIOD: This policy applies only to accidents and losses which occur during the policy period shown in the Declarations.\n\n5. PREMIUM: The premium for this policy is based on information we received from you and other sources. Changes in your policy or driving record may result in premium changes.',
              fontSize: 10,
              fontFamily: 'Inter',
              lineHeight: 1.6,
              textAlign: 'justify',
            }),
          },
          {
            id: 'acknowledgment-title',
            type: 'text-label',
            position: { x: 20, y: 155 },
            size: { width: 170, height: 8 },
            properties: createTextLabelProperties({
              content: 'Acknowledgment',
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'acknowledgment-text',
            type: 'paragraph',
            position: { x: 20, y: 168 },
            size: { width: 170, height: 25 },
            properties: createParagraphProperties({
              content:
                'By signing below, I acknowledge that I have read and understand the terms and conditions of this policy. I confirm that all information provided is accurate and complete to the best of my knowledge.',
              fontSize: 10,
              fontFamily: 'Inter',
              lineHeight: 1.5,
              textAlign: 'left',
            }),
          },
          {
            id: 'signature-insured',
            type: 'signature-box',
            position: { x: 20, y: 200 },
            size: { width: 80, height: 30 },
            properties: createSignatureBoxProperties({
              signerName: 'Policyholder Signature',
              signerTitle: 'Named Insured',
              dateRequired: true,
              showLine: true,
            }),
          },
          {
            id: 'signature-agent',
            type: 'signature-box',
            position: { x: 110, y: 200 },
            size: { width: 80, height: 30 },
            properties: createSignatureBoxProperties({
              signerName: 'Agent Signature',
              signerTitle: 'Licensed Agent',
              dateRequired: true,
              showLine: true,
            }),
          },
        ],
      },
    ],
    headerFooter: {
      defaultHeader: {
        height: 20,
        components: [
          {
            id: 'header-logo-placeholder',
            type: 'text-label',
            position: { x: 10, y: 5 },
            size: { width: 40, height: 10 },
            properties: createTextLabelProperties({
              content: '🛡️ InsureCo',
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#2563eb',
              textAlign: 'left',
            }),
          },
          {
            id: 'header-policy-ref',
            type: 'text-label',
            position: { x: 150, y: 5 },
            size: { width: 50, height: 10 },
            properties: createTextLabelProperties({
              content: '{{policyNumber}}',
              fontSize: 9,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#6b7280',
              textAlign: 'right',
            }),
          },
        ],
      },
      defaultFooter: {
        height: 12,
        components: [
          {
            id: 'footer-page',
            type: 'text-label',
            position: { x: 85, y: 2 },
            size: { width: 40, height: 8 },
            properties: createTextLabelProperties({
              content: 'Page {{pageNumber}} of {{totalPages}}',
              fontSize: 9,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#9ca3af',
              textAlign: 'center',
            }),
          },
        ],
      },
      firstPageHeader: {
        height: 0,
        components: [],
      },
    },
    variables: {
      policyNumber: '',
      insuredName: '',
      effectiveDate: '',
      expirationDate: '',
    },
  },
};
