// Professional Invoice Template
// Clean and professional invoice template for billing

import type { Template } from '@/lib/types/document.types';
import {
  createTextLabelProperties,
  createTextFieldProperties,
  createDateFieldProperties,
  createTableProperties,
  createParagraphProperties,
  createDividerProperties,
} from '../defaults';

export const INVOICE_BASIC: Template = {
  id: 'invoice-basic',
  name: 'Professional Invoice',
  description: 'Clean and professional invoice template for billing',
  category: 'business',
  isBuiltIn: true,
  createdAt: '2025-01-01T00:00:00Z',
  updatedAt: '2025-01-01T00:00:00Z',
  content: {
    pages: [
      {
        id: 'invoice-page-1',
        pageNumber: 1,
        headerType: 'none',
        footerType: 'default',
        components: [
          {
            id: 'invoice-title',
            type: 'text-label',
            position: { x: 140, y: 15 },
            size: { width: 50, height: 15 },
            properties: createTextLabelProperties({
              content: 'INVOICE',
              fontSize: 28,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#2563eb',
              textAlign: 'right',
            }),
          },
          {
            id: 'company-name',
            type: 'text-label',
            position: { x: 20, y: 15 },
            size: { width: 80, height: 10 },
            properties: createTextLabelProperties({
              content: 'Your Company Name',
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'company-address',
            type: 'paragraph',
            position: { x: 20, y: 28 },
            size: { width: 80, height: 20 },
            properties: createParagraphProperties({
              content: '123 Business Street\nCity, State 12345\nPhone: (555) 123-4567',
              fontSize: 9,
              fontFamily: 'Inter',
              lineHeight: 1.4,
              textAlign: 'left',
            }),
          },
          {
            id: 'invoice-number-label',
            type: 'text-label',
            position: { x: 140, y: 35 },
            size: { width: 30, height: 6 },
            properties: createTextLabelProperties({
              content: 'Invoice #:',
              fontSize: 10,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#374151',
              textAlign: 'right',
            }),
          },
          {
            id: 'invoice-number-field',
            type: 'text-field',
            position: { x: 172, y: 33 },
            size: { width: 25, height: 10 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'invoice_number',
              placeholder: '001',
              required: true,
              fontSize: 10,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'invoice-date-label',
            type: 'text-label',
            position: { x: 140, y: 48 },
            size: { width: 30, height: 6 },
            properties: createTextLabelProperties({
              content: 'Date:',
              fontSize: 10,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#374151',
              textAlign: 'right',
            }),
          },
          {
            id: 'invoice-date-field',
            type: 'date-field',
            position: { x: 172, y: 46 },
            size: { width: 25, height: 10 },
            properties: createDateFieldProperties({
              label: '',
              fieldName: 'invoice_date',
              format: 'MM/DD/YYYY',
              required: true,
            }),
          },
          {
            id: 'bill-to-label',
            type: 'text-label',
            position: { x: 20, y: 60 },
            size: { width: 30, height: 8 },
            properties: createTextLabelProperties({
              content: 'Bill To:',
              fontSize: 11,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'client-name-field',
            type: 'text-field',
            position: { x: 20, y: 70 },
            size: { width: 80, height: 10 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'client_name',
              placeholder: 'Client Name',
              required: true,
              fontSize: 10,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'client-address-field',
            type: 'text-field',
            position: { x: 20, y: 82 },
            size: { width: 80, height: 10 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'client_address',
              placeholder: 'Client Address',
              required: false,
              fontSize: 10,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'items-table',
            type: 'table',
            position: { x: 20, y: 105 },
            size: { width: 170, height: 60 },
            properties: createTableProperties({
              columnDefinitions: [
                { type: 'relative', width: 4 },
                { type: 'relative', width: 1 },
                { type: 'relative', width: 1 },
                { type: 'relative', width: 1 },
              ],
              headers: ['Description', 'Qty', 'Rate', 'Amount'],
              data: [
                ['', '', '', ''],
                ['', '', '', ''],
                ['', '', '', ''],
                ['', '', '', ''],
                ['', '', '', ''],
              ],
              showHeader: true,
              borderColor: '#e5e7eb',
              headerBackground: '#2563eb',
              headerTextColor: '#ffffff',
            }),
          },
          {
            id: 'subtotal-label',
            type: 'text-label',
            position: { x: 130, y: 175 },
            size: { width: 30, height: 6 },
            properties: createTextLabelProperties({
              content: 'Subtotal:',
              fontSize: 10,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#374151',
              textAlign: 'right',
            }),
          },
          {
            id: 'subtotal-field',
            type: 'text-field',
            position: { x: 165, y: 173 },
            size: { width: 25, height: 8 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'subtotal',
              placeholder: '$0.00',
              required: false,
              fontSize: 10,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'tax-label',
            type: 'text-label',
            position: { x: 130, y: 186 },
            size: { width: 30, height: 6 },
            properties: createTextLabelProperties({
              content: 'Tax:',
              fontSize: 10,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#374151',
              textAlign: 'right',
            }),
          },
          {
            id: 'tax-field',
            type: 'text-field',
            position: { x: 165, y: 184 },
            size: { width: 25, height: 8 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'tax',
              placeholder: '$0.00',
              required: false,
              fontSize: 10,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'total-divider',
            type: 'divider',
            position: { x: 130, y: 196 },
            size: { width: 60, height: 1 },
            properties: createDividerProperties({
              orientation: 'horizontal',
              thickness: 1,
              color: '#374151',
            }),
          },
          {
            id: 'total-label',
            type: 'text-label',
            position: { x: 130, y: 200 },
            size: { width: 30, height: 8 },
            properties: createTextLabelProperties({
              content: 'Total:',
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'right',
            }),
          },
          {
            id: 'total-field',
            type: 'text-field',
            position: { x: 165, y: 198 },
            size: { width: 25, height: 10 },
            properties: createTextFieldProperties({
              label: '',
              fieldName: 'total',
              placeholder: '$0.00',
              required: true,
              fontSize: 12,
              fontFamily: 'Inter',
            }),
          },
          {
            id: 'notes-label',
            type: 'text-label',
            position: { x: 20, y: 220 },
            size: { width: 30, height: 8 },
            properties: createTextLabelProperties({
              content: 'Notes:',
              fontSize: 11,
              fontFamily: 'Inter',
              fontWeight: 'bold',
              color: '#1a1a1a',
              textAlign: 'left',
            }),
          },
          {
            id: 'notes-content',
            type: 'paragraph',
            position: { x: 20, y: 230 },
            size: { width: 100, height: 20 },
            properties: createParagraphProperties({
              content: 'Payment is due within 30 days.\nThank you for your business!',
              fontSize: 9,
              fontFamily: 'Inter',
              lineHeight: 1.4,
              textAlign: 'left',
            }),
          },
        ],
      },
    ],
    headerFooter: {
      defaultHeader: { height: 0, components: [] },
      defaultFooter: {
        height: 10,
        components: [
          {
            id: 'invoice-footer',
            type: 'text-label',
            position: { x: 20, y: 2 },
            size: { width: 170, height: 6 },
            properties: createTextLabelProperties({
              content: 'Thank you for your business! • Payment terms: Net 30',
              fontSize: 8,
              fontFamily: 'Inter',
              fontWeight: 'normal',
              color: '#9ca3af',
              textAlign: 'center',
            }),
          },
        ],
      },
    },
    variables: {},
  },
};
